### ISSUE TITLE
Custom Issue for Community Interest

### ISSUE THREAD

**Issue by shannonrankin** [NMFS-PAM-Glider/GliderRodeo#18]
Create a Custom Issue (form) for community members to share information or express interest

- [ ] Do they want to participate in the Glider Rodeo? What info do we want from them?
- [ ] Do they know of technology under development? What info can they share?
- [ ] Do they want to suggest metrics? Provide link to google form
- [ ] Put a link to this Issue in the Github Rodeo website under 'contact us'
- [ ] For those issues-- have emails sent to (who? Shannon, Erin, Selene?)

**Comment by sfregosi** [comment]
@shannonrankin I created a branch to work on this and pushed two initial templates that we will want to tweak. 

There are two types of issue templates - written in markdown syntax or entirely as a yaml. I've only previously worked with the markdown type. The markdown ones are very simple; they just require some header info at the top and some text in the body as if you were writing any type of issue. I've had good success with using these to create issues for repeated tasks, which might not be what we are looking for here. 

I pulled and started to modify the GitHub example for the yaml type. It's definitely a work in progress. I'd like to see it rendered and expand from there. It may be more of the 'form' approach we are looking for. 

In either case, they need to be stored in the `.github/ISSUE_TEMPLATE` folder. 

In the example I have there is also a `config.yml`. I'm not sure if that is required so I just copied it over just in case. I believe this is the default created by GitHub.

**Comment by shannonrankin** [comment]
Alrighty! For the moment I will keep my ideas here until I get a feel for this...
(1) We have the google form for the metrics, so we can eliminate this from here for simplicity, unless you think this would be easier than the google form. 
(2) Should we make each a separate 'form'? If they know a technology, click on this link to send info. If they want to participate, click on this link. ??
(3) Participation-- contact info, also space for comment. Maybe check Hawaii, West Coast (or both)
(4) Technology-- contact info, website, attach reports or papers, comment box.

The yaml version looks easy enough to modify, perhaps one for technology, one for participation. Can then have different assignees based on that answer? 

Hmmm.... Ok, This is a great start. Sometime when we both have time, perhaps we can see how to move forward? Or, let me know your thoughts here.  THanks!

**Comment by sfregosi** [comment]
I agree that breaking things up into pieces (metrics, technology, participation, contact, etc) is a very good idea. 

As for Google Forms vs Issues here, maybe better to actually discuss that with spoken words. I think some folks may be more comfortable with Google Forms, you already put a lot of work in there, and it does spit everything out in a nice little table. GitHub Issues allows for back and forth discussion, but would require us to transcribe the info into a central table and is less known to people than Google Forms. Maybe we do both, or some combo of them...

Do you want to have this in place before UG2? I think that is doable. I could talk this afternoon. I'm on the road a bunch tomorrow so will be in and out but will have time to work on things if we have a plan.

**Comment by shannonrankin** [comment]
I'm available until about 2pm (after that some of the time i'm available to
chat via phone while on the road). Yes, we should have this in place before
UG2 (Tuesday morning). Let me know when you have time to chat...

**Comment by shannonrankin** [comment]
Will use google forms via ***@***.*** email for the interim.
These prelim forms have been created, and links to forms entered into
website. Selene will work on custom Issues/Forms (to use at a later date,
for a later need).
Links to forms, below (please feel free to edit!):
New PAM Glider Technology <https://forms.gle/RS5U3c9UphnmnjTN8>
Glider Rodeo Participation <https://forms.gle/Q1DRELQy8Y43hCBD8>
Glider Rodeo Alternative Data <https://forms.gle/dvSzq6rcK7XjM6UR8>
Glider Rodeo Metrics <https://forms.gle/iELwHBJ7pEtFG1Q46>

**Comment by sfregosi** [comment]
Marking this as complete - we transitioned to Google Form
